#spring:
#  data:
#    cassandra:
#      contact-points: localhost
#      port: 9042
#      keyspace-name: simple_crud
#      #username: cassandra
#      #password: cassandra
#      schema-act: create_if_not_exists